
##############################################################
# This Script has been generated by Ixia ScriptGen
#      Software Version : ixos 4.10.250.18 SP6         
##############################################################


package req IxTclHal

# Command Option Mode - Full (generate full configuration)


if {[isUNIX]} {
	if {[ixConnectToTclServer 192.168.24.194]} {
		ixPuts "Error connecting to Tcl Server 192.168.24.194 "
		return 1
	}
}


######### Chassis- 192.168.24.194 #########

ixConnectToChassis   {192.168.24.194}

chassis                      get               "192.168.24.194"
set chassis	  [chassis cget -id]
set owner "11"
ixLogin                      $owner            

set card     10
set lanport     1
set wanport     2
set portList {}

ixPortClearOwnership $chassis $card $lanport force
ixPortClearOwnership $chassis $card $wanport force

set lan_da1 "00 09 00 00 01 01"
set lan_sa1 "00 09 00 00 02 01"
set lan_da2 "00 09 00 00 01 02"
set lan_sa2 "00 09 00 00 02 02"
set lan_da3 "00 09 00 00 01 03"
set lan_sa3 "00 09 00 00 02 03"
set lan_da4 "00 09 00 00 01 04"
set lan_sa4 "00 09 00 00 02 04"

set wan_da1 "00 09 00 00 02 01"
set wan_sa1 "00 09 00 00 01 01"

######### Card Type : 10/100/1000 STXS4 ############

card                         setDefault        
card                         config            -txFrequencyDeviation               0
card                         set               $chassis $card
card                         write             $chassis $card

######### Chassis-192.168.24.194 Card-10  Port-1 #########

port                         setFactoryDefaults $chassis $card $lanport
port                         setPhyMode        $::portPhyModeCopper $chassis $card $lanport

filter                       setDefault        
filter                       config            -captureTriggerDA                   addr1
filter                       config            -captureTriggerSA                   addr1
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       set               $chassis $card $lanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $wan_da1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA1                                $wan_sa1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               set               $chassis $card $lanport
lappend                      portList          [list $chassis $card $lanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          

######### Chassis-192.168.24.194 Card-10  Port-1 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               "stream1"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                9999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            54400.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        46
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpCustom
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       1
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0010XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
#  Stream 2
stream                       setDefault        
stream                       config            -name                               "stream2"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                9999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            54400.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa2
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da2
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        46
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpCustom
ip                           config            -dscpValue                          0x10
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
#  Stream 3
stream                       setDefault        
stream                       config            -name                               "stream3"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             160.0
stream                       config            -ifgMAX                             224.0
stream                       config            -ibg                                9999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            54400.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa3
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da3
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        46
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpCustom
ip                           config            -dscpValue                          0x20
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             150
vlan                         config            -userPriority                       1
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0010XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
#  Stream 4
stream                       setDefault        
stream                       config            -name                               "stream4"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                9999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            54400.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa4
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da4
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        46
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             150
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
ixWriteConfigToHardware      portList          -noProtocolServer

######### Card Type : 10/100/1000 STXS4 ############

card                         setDefault        
card                         config            -txFrequencyDeviation               0
card                         set               $chassis $card
card                         write             $chassis $card

######### Chassis-192.168.24.194 Card-10  Port-2 #########

port                         setFactoryDefaults $chassis $card $wanport
port                         setPhyMode        $::portPhyModeCopper $chassis $card $wanport

filter                       setDefault        
filter                       config            -captureTriggerDA                   addr1
filter                       config            -captureTriggerSA                   addr1
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       set               $chassis $card $wanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $lan_da1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA1                                $lan_sa1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               set               $chassis $card $wanport
lappend                      portList          [list $chassis $card $wanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          

######### Chassis-192.168.24.194 Card-10  Port-2 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               "stream1"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                9999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            54400.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $wan_sa1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $wan_da1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanStacked
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        42
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $wanport

stackedVlan                  setDefault        
set vlanPosition 1
vlan                         setDefault        
vlan                         config            -vlanID                             300
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
stackedVlan                  setVlan           $vlanPosition

incr                         vlanPosition      
vlan                         setDefault        
vlan                         config            -vlanID                             150
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
stackedVlan                  setVlan           $vlanPosition
stackedVlan                  set               $chassis $card $wanport


if {[port isValidFeature $chassis $card $wanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $wanport
}


if {[port isValidFeature $chassis $card $wanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $wanport
}

stream                       set               $chassis $card $wanport $streamId
incr                         streamId          
ixWriteConfigToHardware      portList          -noProtocolServer



after 2000
ixPuts "################### lanport upstream ######################"

ixClearPortStats $chassis $card $lanport
ixClearPortStats $chassis $card $wanport
after 1000

ixStartPortTransmit $chassis $card $lanport
ixStartPortCapture $chassis $card $wanport
after 5000
#ixCheckPortTransmitDone $chassis $card $lanport
ixStopPortCapture $chassis $card $wanport
ixStopPortTransmit $chassis $card $lanport

captureBuffer get $chassis $card $wanport 1 20

set Flag1 0
set Mark1 0
for {set i 1} {$i <= 20} {incr i} {
	if { [captureBuffer getframe $i] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 11]
	       set tarValue [format "%s %s" $lan_da1 $lan_sa1 ]
	       if {$typeField == $tarValue	} {           
			  ixPuts "error ! receiving upstream stream1."
	          break
	          } else { 
	                puts $typeField
	                incr Mark1
	          }
    }	
}
if {$Mark1 == 20} {
	incr Flag1
	ixPuts "It is expected that not receiving upstream stream1."
}


set Flag2 0
set Mark2 0
for {set i 1} {$i <= 20} {incr i} {
	if { [captureBuffer getframe $i] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 11]
	       set tarValue [format "%s %s" $lan_da2 $lan_sa2 ]
	       if {$typeField == $tarValue	} {           
			  ixPuts "error ! receiving upstream stream2."
	          break
	          } else { 
	                puts $typeField
	                incr Mark2
	          }
    }	
}
if {$Mark2 == 20} {
	incr Flag2
	ixPuts "It is expected that not receiving upstream stream2."
}

set Flag3 0
set Mark3 0
for {set i 1} {$i <= 20} {incr i} {
	if { [captureBuffer getframe $i] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 11]
	       set tarValue [format "%s %s" $lan_da3 $lan_sa3 ]
	       if {$typeField == $tarValue	} {           
			  ixPuts "error ! receiving upstream stream3."
	          break
	          } else { 
	                puts $typeField
	                incr Mark3
	          }
    }	
}
if {$Mark3 == 20} {
	incr Flag3
	ixPuts "It is expected that not receiving upstream stream3."
}


set Flag4 0
set Mark4 0
for {set j 1} {$j <= 20} {incr j} {
	if { [captureBuffer getframe $j] } {
	    ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	    break
	} else {
	     set capFrame [captureBuffer cget -frame]
	     set typeField [lrange $capFrame 0 19]
	     set tarValue [format "%s %s 81 00 41 2C 81 00 40 96" $lan_da4 $lan_sa4 ]
	     if {$typeField == $tarValue} {
            incr Flag4
	        ixPuts "It is expected that receiving a outerVlan=300&Priority=2 innerVLAN=150&priority=2 upstream stream4 ."
	     break
	     } else { 
	           puts $typeField
	           incr Mark4
	     }
    }
}	
if {$Mark4 == 20} {
    ixPuts "error ! not receiving outerVlan=300&Priority=2 innerVLAN=150&priority=2 upstream stream4"
}


ixPuts "################### wanport downstream ######################"

ixClearPortStats $chassis $card $wanport
ixClearPortStats $chassis $card $lanport
after 1000
ixStartPortTransmit $chassis $card $wanport
ixStartPortCapture $chassis $card $lanport
after 5000
#ixCheckPortTransmitDone $chassis $card $lanport
ixStopPortCapture $chassis $card $lanport
ixStopPortTransmit $chassis $card $wanport

captureBuffer get $chassis $card $lanport 1 10


#captureBuffer get $chassis $card $lanport 1 10 
#这个API有问题,TCL API执行成功返回0 不进入if语句；执行失败返回1，进入if语句;但是这个API不管成功失败都是返回0都不会进入if

set Flag5 0
set Mark5 0
for {set r 1} {$r <= 10} {incr r} {
	if { [captureBuffer getframe $r] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $lanport"	
	   break
	} else {
		#judge about vlan
		set capFrame [captureBuffer cget -frame]
		set typeField [lrange $capFrame 0 15]
		set tarValue [format "%s %s 81 00 40 96" $wan_da1 $wan_sa1 ]
	     if {$typeField == $tarValue} {
            incr Flag5
	        ixPuts "It is expected that receiving a VLAN=150&priority=2 downstream stream ."
	     break
	     } else { 
	           puts $typeField
	           incr Mark5
	     }
    }
}	
if {$Mark5 == 20} {
    ixPuts "error ! not receiving a VLAN=150&priority=2 downstream stream"
}

set Flag [expr $Flag1 + $Flag2 + $Flag3 + $Flag4 + $Flag5]
if {$Flag == 5} {
	ixPuts "#########################  result  #####################"
	puts "this case pass!"
	ixPuts "########################################################"
} else {
	ixPuts "#########################  result  #####################"
	puts "this case fail!"
	ixPuts "########################################################"
}

