
##############################################################
# This Script has been generated by Ixia ScriptGen
#      Software Version : ixos 4.10.250.18 SP6         
##############################################################


package req IxTclHal

# Command Option Mode - Full (generate full configuration)


if {[isUNIX]} {
	if {[ixConnectToTclServer 192.168.24.194]} {
		ixPuts "Error connecting to Tcl Server 192.168.24.194 "
		return 1
	}
}


######### Chassis- 192.168.24.194 #########

ixConnectToChassis   {192.168.24.194}

chassis                      get               "192.168.24.194"
set chassis	  [chassis cget -id]
set card     10
set lanport     1
set wanport     2
set portList {}

ixPortClearOwnership $chassis $card $lanport force
ixPortClearOwnership $chassis $card $wanport force

set lan_da1 "00 09 00 00 01 01"
set lan_sa1 "00 09 00 00 02 01"
set lan_da2 "00 09 00 00 01 02"
set lan_sa2 "00 09 00 00 02 02"

set wan_da1 "00 09 00 00 02 01"
set wan_sa1 "00 09 00 00 01 01"
set wan_da2 "00 09 00 00 02 02"
set wan_sa2 "00 09 00 00 01 02"

######### Card Type : 10/100/1000 STXS4 ############

card                         setDefault        
card                         config            -txFrequencyDeviation               0
card                         set               $chassis $card
card                         write             $chassis $card

######### Chassis-192.168.24.194 Card-10  Port-1 #########

port                         setFactoryDefaults $chassis $card $lanport
port                         setPhyMode        $::portPhyModeCopper $chassis $card $lanport

filter                       setDefault        
filter                       config            -captureTriggerDA                   addr1
filter                       config            -captureTriggerSA                   addr1
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       set               $chassis $card $wanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $wan_da1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA1                                $wan_sa1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               set               $chassis $card $lanport
lappend                      portList          [list $chassis $card $lanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          

######### Chassis-192.168.24.194 Card-10  Port-1 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               "stream1"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999424.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             96.0
stream                       config            -ifgMAX                             160.0
stream                       config            -ibg                                9999424.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999424.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0672
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            51200.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          64
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       64
stream                       config            -frameSizeMAX                       64
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        42
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
#  Stream 2
stream                       setDefault        
stream                       config            -name                               "stream2"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9999424.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             96.0
stream                       config            -ifgMAX                             160.0
stream                       config            -ibg                                9999424.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9999424.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0672
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            51200.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $lan_sa2
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $lan_da2
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          64
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       64
stream                       config            -frameSizeMAX                       64
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        42
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $lanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       3
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0110XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
ixWriteConfigToHardware      portList          -noProtocolServer


######### Card Type : 10/100/1000 STXS4 ############

card                         setDefault        
card                         config            -txFrequencyDeviation               0
card                         set               $chassis $card
card                         write             $chassis $card

######### Chassis-192.168.24.194 Card-10  Port-2 #########

port                         setFactoryDefaults $chassis $card $wanport
port                         setPhyMode        $::portPhyModeCopper $chassis $card $wanport

port                         setDefault        
port                         config            -speed                              100
port                         config            -duplex                             full
port                         config            -flowControl                        false
port                         config            -directedAddress                    "01 80 C2 00 00 01"
port                         config            -multicastPauseAddress              "01 80 C2 00 00 01"
port                         config            -loopback                           false
port                         config            -transmitMode                       portTxPacketStreams
port                         config            -receiveMode                        [expr $::portCapture]
port                         config            -autonegotiate                      false
port                         config            -advertise100FullDuplex             true
port                         config            -advertise100HalfDuplex             false
port                         config            -advertise10FullDuplex              false
port                         config            -advertise10HalfDuplex              false
port                         config            -advertise1000FullDuplex            false
port                         config            -portMode                           portEthernetMode
port                         config            -rxTxMode                           gigNormal
port                         config            -ignoreLink                         false
port                         config            -advertiseAbilities                 portAdvertiseNone
port                         config            -timeoutEnable                      true
port                         config            -negotiateMasterSlave               1
port                         config            -masterSlave                        portSlave
port                         config            -enableSimulateCableDisconnect      false
port                         config            -enableAutoDetectInstrumentation    false
port                         config            -enableRepeatableLastRandomPattern  false
port                         config            -transmitClockDeviation             0
port                         config            -preEmphasis                        preEmphasis0
port                         config            -MacAddress                         "00 de bb 00 00 01"
port                         config            -DestMacAddress                     "00 de bb 00 00 02"
port                         config            -name                               "wan"
port                         config            -numAddresses                       1
port                         config            -enableManualAutoNegotiate          false
port                         config            -enablePhyPolling                   true
port                         set               $chassis $card $wanport
stat                         setDefault        
stat                         config            -mode                               statNormal
stat                         config            -enableProtocolServerStats          true
stat                         config            -enableArpStats                     true
stat                         config            -enablePosExtendedStats             true
stat                         config            -enableTemperatureSensorsStats      true
stat                         config            -enableAtmOamStats                  false
stat                         config            -enableDhcpStats                    false
stat                         config            -enableDhcpV6Stats                  false
stat                         config            -includeRprPayloadFcsInCrc          true
stat                         config            -enableValidStats                   false
stat                         config            -enableBgpStats                     false
stat                         config            -enableIcmpStats                    true
stat                         config            -enableOspfStats                    false
stat                         config            -enableIsisStats                    false
stat                         config            -enableRsvpStats                    false
stat                         config            -enableLdpStats                     false
stat                         config            -enableIgmpStats                    false
stat                         config            -enableOspfV3Stats                  false
stat                         config            -enablePimsmStats                   false
stat                         config            -enableMldStats                     false
stat                         config            -enableStpStats                     false
stat                         config            -enableEigrpStats                   false
stat                         set               $chassis $card $wanport

ipAddressTable               setDefault        
ipAddressTable               config            -defaultGateway                     "0.0.0.0"
ipAddressTable               set               $chassis $card $wanport

interfaceTable               select            $chassis $card $wanport
interfaceTable               setDefault        
interfaceTable               config            -dhcpV4RequestRate                  0
interfaceTable               config            -dhcpV6RequestRate                  0
interfaceTable               set               
interfaceTable               clearAllInterfaces 
protocolServer               setDefault        
protocolServer               config            -enableArpResponse                  false
protocolServer               config            -enablePingResponse                 false
protocolServer               config            -enableIgmpQueryResponse            false
protocolServer               config            -enableOspfService                  false
protocolServer               config            -enableBgp4Service                  false
protocolServer               config            -enableIsisService                  false
protocolServer               config            -enableRsvpService                  false
protocolServer               config            -enableRipService                   false
protocolServer               config            -enableLdpService                   false
protocolServer               config            -enableRipngService                 false
protocolServer               config            -enableMldService                   false
protocolServer               config            -enableOspfV3Service                false
protocolServer               config            -enablePimsmService                 false
protocolServer               config            -enableStpService                   false
protocolServer               config            -enableBgp4CreateInterface          false
protocolServer               config            -enableIsisCreateInterface          false
protocolServer               config            -enableOspfCreateInterface          false
protocolServer               config            -enableRipCreateInterface           false
protocolServer               config            -enableRsvpCreateInterface          false
protocolServer               config            -enableIgmpCreateInterface          false
protocolServer               set               $chassis $card $wanport

flexibleTimestamp            setDefault        
flexibleTimestamp            config            -type                               timestampBeforeCrc
flexibleTimestamp            config            -offset                             23
flexibleTimestamp            set               $chassis $card $wanport

capture                      setDefault        
capture                      config            -fullAction                         lock
capture                      config            -sliceSize                          8191
capture                      config            -sliceOffset                        0
capture                      config            -trigger                            -1
capture                      config            -filter                             -1
capture                      config            -captureMode                        captureTriggerMode
capture                      config            -continuousFilter                   0
capture                      config            -beforeTriggerFilter                captureBeforeTriggerNone
capture                      config            -afterTriggerFilter                 captureAfterTriggerFilter
capture                      config            -triggerPosition                    1.0
capture                      config            -enableSmallPacketCapture           false
capture                      set               $chassis $card $wanport
filter                       setDefault        
filter                       config            -captureTriggerDA                   addr1
filter                       config            -captureTriggerSA                   addr1
filter                       config            -captureTriggerPattern              anyPattern
filter                       config            -captureTriggerError                errAnyFrame
filter                       config            -captureTriggerFrameSizeEnable      false
filter                       config            -captureTriggerFrameSizeFrom        64
filter                       config            -captureTriggerFrameSizeTo          1518
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureFilterPattern               anyPattern
filter                       config            -captureFilterError                 errAnyFrame
filter                       config            -captureFilterFrameSizeEnable       false
filter                       config            -captureFilterFrameSizeFrom         64
filter                       config            -captureFilterFrameSizeTo           1518
filter                       config            -userDefinedStat1DA                 anyAddr
filter                       config            -userDefinedStat1SA                 anyAddr
filter                       config            -userDefinedStat1Pattern            anyPattern
filter                       config            -userDefinedStat1Error              errAnyFrame
filter                       config            -userDefinedStat1FrameSizeEnable    false
filter                       config            -userDefinedStat1FrameSizeFrom      64
filter                       config            -userDefinedStat1FrameSizeTo        1518
filter                       config            -userDefinedStat2DA                 anyAddr
filter                       config            -userDefinedStat2SA                 anyAddr
filter                       config            -userDefinedStat2Pattern            pattern1
filter                       config            -userDefinedStat2Error              errGoodFrame
filter                       config            -userDefinedStat2FrameSizeEnable    1
filter                       config            -userDefinedStat2FrameSizeFrom      1514
filter                       config            -userDefinedStat2FrameSizeTo        1514
filter                       config            -asyncTrigger1DA                    anyAddr
filter                       config            -asyncTrigger1SA                    anyAddr
filter                       config            -asyncTrigger1Pattern               anyPattern
filter                       config            -asyncTrigger1Error                 errAnyFrame
filter                       config            -asyncTrigger1FrameSizeEnable       false
filter                       config            -asyncTrigger1FrameSizeFrom         64
filter                       config            -asyncTrigger1FrameSizeTo           1518
filter                       config            -asyncTrigger2DA                    anyAddr
filter                       config            -asyncTrigger2SA                    anyAddr
filter                       config            -asyncTrigger2Pattern               anyPattern
filter                       config            -asyncTrigger2Error                 errAnyFrame
filter                       config            -asyncTrigger2FrameSizeEnable       false
filter                       config            -asyncTrigger2FrameSizeFrom         64
filter                       config            -asyncTrigger2FrameSizeTo           1518
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       config            -userDefinedStat1Enable             false
filter                       config            -userDefinedStat2Enable             true
filter                       config            -asyncTrigger1Enable                false
filter                       config            -asyncTrigger2Enable                false
filter                       set               $chassis $card $wanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $lan_da1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -DA2                                "00 00 00 00 00 00"
filterPallette               config            -DAMask2                            "00 00 00 00 00 00"
filterPallette               config            -SA1                                $lan_sa1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA2                                "00 00 00 00 00 00"
filterPallette               config            -SAMask2                            "00 00 00 00 00 00"
filterPallette               config            -pattern1                           "DB 00 0A 02"
filterPallette               config            -patternMask1                       "00 00 00 00 00 00"
filterPallette               config            -pattern2                           00
filterPallette               config            -patternMask2                       00
filterPallette               config            -patternOffset1                     1500
filterPallette               config            -patternOffset2                     12
filterPallette               config            -matchType1                         matchUser
filterPallette               config            -matchType2                         matchUser
filterPallette               config            -patternOffsetType1                 filterPalletteOffsetStartOfFrame
filterPallette               config            -patternOffsetType2                 filterPalletteOffsetStartOfFrame
filterPallette               config            -gfpErrorCondition                  gfpErrorsOr
filterPallette               config            -enableGfptHecError                 true
filterPallette               config            -enableGfpeHecError                 true
filterPallette               config            -enableGfpPayloadCrcError           true
filterPallette               config            -enableGfpBadFcsError               true
filterPallette               set               $chassis $card $wanport
lappend                      portList          [list $chassis $card $wanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          

######### Chassis-192.168.24.194 Card-10  Port-2 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               "stream1"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9994240.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             1920.0
stream                       config            -ifgMAX                             2560.0
stream                       config            -ibg                                9994240.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9994240.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0672
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            51200.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $wan_sa1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $wan_da1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          64
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       64
stream                       config            -frameSizeMAX                       64
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        42
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolUdp
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "192.168.4.121"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "224.4.4.1"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $wanport
udp                          setDefault        
udp                          config            -sourcePort                         unassignedPort
udp                          config            -destPort                           unassignedPort
udp                          config            -checksum                           "2b ec "
udp                          config            -enableChecksum                     false
udp                          config            -length                             22
udp                          config            -lengthOverride                     false
udp                          config            -enableChecksumOverride             false
udp                          config            -checksumMode                       validChecksum
udp                          set               $chassis $card $wanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       0
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0000XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $wanport

if {[port isValidFeature $chassis $card $wanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $wanport
}


if {[port isValidFeature $chassis $card $wanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $wanport
}

stream                       set               $chassis $card $wanport $streamId
incr                         streamId          
#  Stream 2
stream                       setDefault        
stream                       config            -name                               "stream2"
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          3
stream                       config            -ifg                                9994240.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             1920.0
stream                       config            -ifgMAX                             2560.0
stream                       config            -ibg                                9994240.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                9994240.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0672
stream                       config            -fpsRate                            100.0
stream                       config            -bpsRate                            51200.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $wan_sa2
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $wan_da2
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          64
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       64
stream                       config            -frameSizeMAX                       64
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "08 00"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               ipV4
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       ethernetII
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false
ip                           setDefault        
ip                           config            -precedence                         routine
ip                           config            -delay                              normalDelay
ip                           config            -throughput                         normalThruput
ip                           config            -reliability                        normalReliability
ip                           config            -identifier                         0
ip                           config            -cost                               0
ip                           config            -reserved                           0
ip                           config            -totalLength                        42
ip                           config            -lengthOverride                     false
ip                           config            -fragment                           may
ip                           config            -lastFragment                       last
ip                           config            -fragmentOffset                     0
ip                           config            -ttl                                64
ip                           config            -ipProtocol                         ipV4ProtocolReserved255
ip                           config            -useValidChecksum                   true
ip                           config            -sourceIpAddr                       "0.0.0.0"
ip                           config            -sourceIpMask                       "255.0.0.0"
ip                           config            -sourceIpAddrMode                   ipIdle
ip                           config            -sourceIpAddrRepeatCount            10
ip                           config            -sourceClass                        classA
ip                           config            -enableSourceSyncFromPpp            false
ip                           config            -destIpAddr                         "0.0.0.0"
ip                           config            -destIpMask                         "255.0.0.0"
ip                           config            -destIpAddrMode                     ipIdle
ip                           config            -destIpAddrRepeatCount              10
ip                           config            -destClass                          classA
ip                           config            -destMacAddr                        "00 DE BB 00 00 02"
ip                           config            -destDutIpAddr                      "0.0.0.0"
ip                           config            -options                            ""
ip                           config            -enableDestSyncFromPpp              false
ip                           config            -qosMode                            ipV4ConfigTos
ip                           config            -dscpMode                           ipV4DscpDefault
ip                           config            -dscpValue                          0x00
ip                           config            -classSelector                      ipV4DscpClass1
ip                           config            -assuredForwardingClass             ipV4DscpAssuredForwardingClass1
ip                           config            -assuredForwardingPrecedence        ipV4DscpPrecedenceLowDrop
ip                           set               $chassis $card $wanport

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       1
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0010XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $wanport

if {[port isValidFeature $chassis $card $wanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $wanport
}


if {[port isValidFeature $chassis $card $wanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $wanport
}

stream                       set               $chassis $card $wanport $streamId
incr                         streamId          
ixWriteConfigToHardware      portList          -noProtocolServer


after 2000
ixPuts "################### lanport upstream ######################"
#ixPuts "Removal of port information status message"
ixClearPortStats $chassis $card $lanport
ixClearPortStats $chassis $card $wanport
after 1000
#ixPuts "Match flow open port, message collection and contrast"
ixStartPortTransmit $chassis $card $lanport
ixStartPortCapture $chassis $card $wanport
after 5000
#ixCheckPortTransmitDone $chassis $card $lanport
ixStopPortCapture $chassis $card $wanport
ixStopPortTransmit $chassis $card $lanport

captureBuffer get $chassis $card $wanport 1 10

set Flag1 0
set Mark1 0
for {set i 1} {$i <= 10} {incr i} {
	if { [captureBuffer getframe $i] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	      set capFrame [captureBuffer cget -frame]
	      set typeField [lrange $capFrame 0 15]
	      set tarValue [format "%s %s 81 00 00 64" $lan_da1 $lan_sa1 ]
		  if {$typeField == $tarValue	} {
             incr Flag1
	         ixPuts "It is expected that receiving a Vlan=100 Priority=0 upstream stream1 ."
	         break
	      } else { 
	             incr Mark1 
	             puts $typeField
	      }
    }	
}
if {$Mark1 == 10} {
    ixPuts "error ! not receiving a Vlan=100 Priority=0 upstream stream1"
}


set Flag2 0
set Mark2 0
for {set j 1} {$j <= 10} {incr j} {
	if { [captureBuffer getframe $j] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	      set capFrame [captureBuffer cget -frame]
	      set typeField [lrange $capFrame 0 15]
	      set tarValue [format "%s %s 81 00 20 64" $lan_da2 $lan_sa2 ]
		  if {$typeField == $tarValue	} {
             incr Flag2
	         ixPuts "It is expected that receiving a Vlan=100 Priority=1 upstream stream2 ."
	         break
	      } else { 
	             incr Mark2 
	             puts $typeField
	      }
    }	
}
if {$Mark2 == 10} {
    ixPuts "error ! not receiving a Vlan=100 Priority=1 upstream stream2"
}






ixPuts "################### wanport downstream ######################"
#ixPuts "Removal of port information status message"
ixClearPortStats $chassis $card $wanport
ixClearPortStats $chassis $card $lanport
after 1000

ixStartPortTransmit $chassis $card $wanport
ixStartPortCapture $chassis $card $lanport
after 5000

ixStopPortCapture $chassis $card $lanport
ixStopPortTransmit $chassis $card $wanport

captureBuffer get $chassis $card $lanport 1 10


#TCL API执行成功返回0 不进入if语句；执行失败返回1，进入if语句

set Flag3 0
set Mark3 0
for {set m 1} {$m <= 10} {incr m} {
	if { [captureBuffer getframe $m] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $lanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 15]
	       set tarValue [format "%s %s 81 00 40 64" $wan_da1 $wan_sa1 ]
	       if {$typeField == $tarValue} {
               incr Flag3
	           ixPuts  "It is expected that receiving a Vlan=100 Priority =2 downstream stream1 ."
	           break
	       } else { 
	              puts $typeField
	              incr Mark3
	       }
    }
}	
if {$Mark3 == 10} {
    ixPuts "Error ! not receiving Vlan=100 Priority =2 downstream stream1."
}


set Flag4 0
set Mark4 0
for {set n 1} {$n <= 10} {incr n} {
	if { [captureBuffer getframe $n] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $lanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 15]
	       set tarValue [format "%s %s 81 00 60 64" $wan_da2 $wan_sa2 ]
	       if {$typeField == $tarValue} {
               incr Flag4
	           ixPuts  "It is expected that receiving a Vlan=100 Priority =3 downstream stream2 ."
	           break
	       } else { 
	              puts $typeField
	              incr Mark4
	       }
    }
}	
if {$Mark4 == 10} {
    ixPuts "Error ! not receiving Vlan=100 Priority =3 downstream stream2."
}

set Flag [expr $Flag1 + $Flag2 +$Flag3 +$Flag4 ]
if {$Flag == 4} {
	ixPuts "#########################  result  #####################"
	puts "this case pass!"
	ixPuts "########################################################"
} else {
	ixPuts "#########################  result  #####################"
	puts "this case fail!"
	ixPuts "########################################################"
}



