
##############################################################
# This Script has been generated by Ixia ScriptGen
#      Software Version : ixos 4.10.250.18 SP6         
##############################################################


package req IxTclHal

# Command Option Mode - Full (generate full configuration)


if {[isUNIX]} {
	if {[ixConnectToTclServer 192.168.20.194]} {
		ixPuts "Error connecting to Tcl Server 192.168.20.194 "
		return 1
	}
}


######### Chassis- 192.168.20.194 #########

ixConnectToChassis   {192.168.20.194}

chassis                      get               "192.168.20.194"
set chassis	  [chassis cget -id]
set card     10
set lanport     1
set wanport     2
set portList {}

ixPortClearOwnership $chassis $card $lanport force
ixPortClearOwnership $chassis $card $wanport force
set owner qa
ixLogin     $owner            
#ixPortTakeOwnership chassisID cardID portID force

set da1 "00 09 03 00 01 01"
set sa1 "00 09 03 00 02 01"
set da2 "00 09 03 00 01 02"
set sa2 "00 09 03 00 02 02"
set da3 "00 09 03 00 01 03"
set sa3 "00 09 03 00 02 03"
set da4 "00 09 03 00 01 04"
set sa4 "00 09 03 00 02 04"

######### Card Type : 10/100/1000 STXS4 ############

card                         setDefault        
card                         config            -txFrequencyDeviation               0
card                         set               $chassis $card
card                         write             $chassis $card

######### Chassis-192.168.20.194 Card-10  Port-1 #########

port                         setFactoryDefaults $chassis $card $lanport
port                         setPhyMode        $::portPhyModeCopper $chassis $card $lanport


port                         setDefault        
port                         config            -speed                              1000
port                         config            -duplex                             full
port                         config            -flowControl                        false
port                         config            -directedAddress                    "01 80 C2 00 00 01"
port                         config            -multicastPauseAddress              "01 80 C2 00 00 01"
port                         config            -loopback                           false
port                         config            -transmitMode                       portTxPacketStreams
port                         config            -receiveMode                        [expr $::portCapture]
port                         config            -autonegotiate                      true
port                         config            -advertise100FullDuplex             true
port                         config            -advertise100HalfDuplex             true
port                         config            -advertise10FullDuplex              true
port                         config            -advertise10HalfDuplex              true
port                         config            -advertise1000FullDuplex            true
port                         config            -portMode                           portEthernetMode
port                         config            -rxTxMode                           gigNormal
port                         config            -ignoreLink                         false
port                         config            -advertiseAbilities                 portAdvertiseNone
port                         config            -timeoutEnable                      true
port                         config            -negotiateMasterSlave               1
port                         config            -masterSlave                        portSlave
port                         config            -enableSimulateCableDisconnect      false
port                         config            -enableAutoDetectInstrumentation    false
port                         config            -enableRepeatableLastRandomPattern  false
port                         config            -transmitClockDeviation             0
port                         config            -preEmphasis                        preEmphasis0
port                         config            -MacAddress                         "00 de bb 00 00 01"
port                         config            -DestMacAddress                     "00 de bb 00 00 02"
port                         config            -name                               "lan"
port                         config            -numAddresses                       1
port                         config            -enableManualAutoNegotiate          false
port                         config            -enablePhyPolling                   true
port                         set               $chassis $card $lanport
stat                         setDefault        
stat                         config            -mode                               statNormal
stat                         config            -enableProtocolServerStats          true
stat                         config            -enableArpStats                     true
stat                         config            -enablePosExtendedStats             true
stat                         config            -enableTemperatureSensorsStats      true
stat                         config            -enableAtmOamStats                  false
stat                         config            -enableDhcpStats                    false
stat                         config            -enableDhcpV6Stats                  false
stat                         config            -includeRprPayloadFcsInCrc          true
stat                         config            -enableValidStats                   false
stat                         config            -enableBgpStats                     false
stat                         config            -enableIcmpStats                    true
stat                         config            -enableOspfStats                    false
stat                         config            -enableIsisStats                    false
stat                         config            -enableRsvpStats                    false
stat                         config            -enableLdpStats                     false
stat                         config            -enableIgmpStats                    false
stat                         config            -enableOspfV3Stats                  false
stat                         config            -enablePimsmStats                   false
stat                         config            -enableMldStats                     false
stat                         config            -enableStpStats                     false
stat                         config            -enableEigrpStats                   false
stat                         set               $chassis $card $lanport

ipAddressTable               setDefault        
ipAddressTable               config            -defaultGateway                     "0.0.0.0"
ipAddressTable               set               $chassis $card $lanport
arpServer                    setDefault        
arpServer                    config            -retries                            3
arpServer                    config            -mode                               arpGatewayAndLearn
arpServer                    config            -rate                               208333
arpServer                    config            -requestRepeatCount                 3
arpServer                    set               $chassis $card $lanport

interfaceTable               select            $chassis $card $lanport
interfaceTable               setDefault        
interfaceTable               config            -dhcpV4RequestRate                  0
interfaceTable               config            -dhcpV6RequestRate                  0
interfaceTable               set               
interfaceTable               clearAllInterfaces 
interfaceEntry               clearAllItems     addressTypeIpV6
interfaceEntry               clearAllItems     addressTypeIpV4
interfaceEntry               setDefault        

interfaceIpV4                setDefault        
interfaceIpV4                config            -gatewayIpAddress                   {192.168.3.1}
interfaceIpV4                config            -maskWidth                          24
interfaceIpV4                config            -ipAddress                          {192.168.3.10}
interfaceEntry               addItem           addressTypeIpV4

dhcpV4Properties             removeAllTlvs     
dhcpV4Properties             setDefault        
dhcpV4Properties             config            -clientId                           ""
dhcpV4Properties             config            -serverId                           "0.0.0.0"
dhcpV4Properties             config            -vendorId                           ""
dhcpV4Properties             config            -renewTimer                         0

dhcpV6Properties             removeAllTlvs     
dhcpV6Properties             setDefault        
dhcpV6Properties             config            -iaType                             dhcpV6IaTypePermanent
dhcpV6Properties             config            -iaId                               7264982
dhcpV6Properties             config            -renewTimer                         0

interfaceEntry               config            -enable                             true
interfaceEntry               config            -description                        {LAN}
interfaceEntry               config            -macAddress                         {00 00 00 6E DA D6}
interfaceEntry               config            -eui64Id                            {02 00 00 FF FE 6E DA D6}
interfaceEntry               config            -atmEncapsulation                   atmEncapsulationLLCBridgedEthernetFCS
interfaceEntry               config            -atmMode                            -1
interfaceEntry               config            -atmVpi                             0
interfaceEntry               config            -atmVci                             32
interfaceEntry               config            -enableDhcp                         false
interfaceEntry               config            -enableVlan                         false
interfaceEntry               config            -vlanId                             0
interfaceEntry               config            -vlanPriority                       0
interfaceEntry               config            -enableDhcpV6                       false
interfaceTable               addInterface      interfaceTypeConnected

protocolServer               setDefault        
protocolServer               config            -enableArpResponse                  true
protocolServer               config            -enablePingResponse                 false
protocolServer               config            -enableIgmpQueryResponse            false
protocolServer               config            -enableOspfService                  false
protocolServer               config            -enableBgp4Service                  false
protocolServer               config            -enableIsisService                  false
protocolServer               config            -enableRsvpService                  false
protocolServer               config            -enableRipService                   false
protocolServer               config            -enableLdpService                   false
protocolServer               config            -enableRipngService                 false
protocolServer               config            -enableMldService                   false
protocolServer               config            -enableOspfV3Service                false
protocolServer               config            -enablePimsmService                 false
protocolServer               config            -enableStpService                   false
protocolServer               config            -enableBgp4CreateInterface          false
protocolServer               config            -enableIsisCreateInterface          false
protocolServer               config            -enableOspfCreateInterface          false
protocolServer               config            -enableRipCreateInterface           false
protocolServer               config            -enableRsvpCreateInterface          false
protocolServer               config            -enableIgmpCreateInterface          false
protocolServer               set               $chassis $card $lanport

flexibleTimestamp            setDefault        
flexibleTimestamp            config            -type                               timestampBeforeCrc
flexibleTimestamp            config            -offset                             23
flexibleTimestamp            set               $chassis $card $lanport

capture                      setDefault        
capture                      config            -fullAction                         lock
capture                      config            -sliceSize                          8191
capture                      config            -sliceOffset                        0
capture                      config            -trigger                            -1
capture                      config            -filter                             -1
capture                      config            -captureMode                        captureContinuousMode
capture                      config            -continuousFilter                   1
capture                      config            -beforeTriggerFilter                captureBeforeTriggerNone
capture                      config            -afterTriggerFilter                 captureAfterTriggerFilter
capture                      config            -triggerPosition                    1.0
capture                      config            -enableSmallPacketCapture           false
capture                      set               $chassis $card $lanport
filter                       setDefault        
filter                       config            -captureTriggerDA                   anyAddr
filter                       config            -captureTriggerSA                   anyAddr
filter                       config            -captureTriggerPattern              anyPattern
filter                       config            -captureTriggerError                errAnyFrame
filter                       config            -captureTriggerFrameSizeEnable      false
filter                       config            -captureTriggerFrameSizeFrom        64
filter                       config            -captureTriggerFrameSizeTo          1518
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureFilterPattern               anyPattern
filter                       config            -captureFilterError                 errAnyFrame
filter                       config            -captureFilterFrameSizeEnable       false
filter                       config            -captureFilterFrameSizeFrom         64
filter                       config            -captureFilterFrameSizeTo           1518
filter                       config            -userDefinedStat1DA                 anyAddr
filter                       config            -userDefinedStat1SA                 anyAddr
filter                       config            -userDefinedStat1Pattern            anyPattern
filter                       config            -userDefinedStat1Error              errAnyFrame
filter                       config            -userDefinedStat1FrameSizeEnable    false
filter                       config            -userDefinedStat1FrameSizeFrom      64
filter                       config            -userDefinedStat1FrameSizeTo        1518
filter                       config            -userDefinedStat2DA                 anyAddr
filter                       config            -userDefinedStat2SA                 anyAddr
filter                       config            -userDefinedStat2Pattern            pattern1
filter                       config            -userDefinedStat2Error              errGoodFrame
filter                       config            -userDefinedStat2FrameSizeEnable    1
filter                       config            -userDefinedStat2FrameSizeFrom      1518
filter                       config            -userDefinedStat2FrameSizeTo        1518
filter                       config            -asyncTrigger1DA                    anyAddr
filter                       config            -asyncTrigger1SA                    anyAddr
filter                       config            -asyncTrigger1Pattern               anyPattern
filter                       config            -asyncTrigger1Error                 errAnyFrame
filter                       config            -asyncTrigger1FrameSizeEnable       false
filter                       config            -asyncTrigger1FrameSizeFrom         64
filter                       config            -asyncTrigger1FrameSizeTo           1518
filter                       config            -asyncTrigger2DA                    anyAddr
filter                       config            -asyncTrigger2SA                    anyAddr
filter                       config            -asyncTrigger2Pattern               anyPattern
filter                       config            -asyncTrigger2Error                 errAnyFrame
filter                       config            -asyncTrigger2FrameSizeEnable       false
filter                       config            -asyncTrigger2FrameSizeFrom         64
filter                       config            -asyncTrigger2FrameSizeTo           1518
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       config            -userDefinedStat1Enable             false
filter                       config            -userDefinedStat2Enable             false
filter                       config            -asyncTrigger1Enable                false
filter                       config            -asyncTrigger2Enable                false
filter                       set               $chassis $card $lanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $sa1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -DA2                                "00 00 00 00 00 00"
filterPallette               config            -DAMask2                            "00 00 00 00 00 00"
filterPallette               config            -SA1                                $da1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA2                                "00 00 00 00 00 00"
filterPallette               config            -SAMask2                            "00 00 00 00 00 00"
filterPallette               config            -pattern1                           "DB 00 0A 01"
filterPallette               config            -patternMask1                       "00 00 00 00 00 00"
filterPallette               config            -pattern2                           00
filterPallette               config            -patternMask2                       00
filterPallette               config            -patternOffset1                     1504
filterPallette               config            -patternOffset2                     12
filterPallette               config            -matchType1                         matchUser
filterPallette               config            -matchType2                         matchUser
filterPallette               config            -patternOffsetType1                 filterPalletteOffsetStartOfFrame
filterPallette               config            -patternOffsetType2                 filterPalletteOffsetStartOfFrame
filterPallette               config            -gfpErrorCondition                  gfpErrorsOr
filterPallette               config            -enableGfptHecError                 true
filterPallette               config            -enableGfpeHecError                 true
filterPallette               config            -enableGfpPayloadCrcError           true
filterPallette               config            -enableGfpBadFcsError               true
filterPallette               set               $chassis $card $lanport
lappend                      portList          [list $chassis $card $lanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          


######### Chassis-192.168.20.194 Card-10  Port-1 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               ""
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          1
stream                       config            -ifg                                993920.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             1920.0
stream                       config            -ifgMAX                             2560.0
stream                       config            -ibg                                993920.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                993920.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.704
stream                       config            -fpsRate                            1000.0
stream                       config            -bpsRate                            544000.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $sa1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $da1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "FF FF"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
#stream                       config            -dma                                contPacket
#stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               mac
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       noType
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       2
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0010XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
#  Stream 2
stream                       setDefault        
stream                       config            -name                               ""
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          1
stream                       config            -ifg                                993920.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             1920.0
stream                       config            -ifgMAX                             2560.0
stream                       config            -ibg                                993920.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                993920.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.704
stream                       config            -fpsRate                            1000.0
stream                       config            -bpsRate                            544000.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $sa2
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $da2
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "FF FF"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
#stream                       config            -dma                                advance
#stream                       config            -dma                                contPacket
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               mac
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       noType
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       3
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0100XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $lanport

if {[port isValidFeature $chassis $card $lanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $lanport
}


if {[port isValidFeature $chassis $card $lanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $lanport
}

stream                       set               $chassis $card $lanport $streamId
incr                         streamId          
        
ixWriteConfigToHardware      portList          -noProtocolServer







######### Chassis-192.168.20.194 Card-10  Port-2 #########

port                         setFactoryDefaults $chassis $card $wanport
port                         setPhyMode        $::portPhyModeFiber $chassis $card $wanport
#port                         setPhyMode        $::portPhyModeCopper $chassis $card $wanport

port                         setDefault        
port                         config            -speed                              1000
port                         config            -duplex                             full
port                         config            -flowControl                        false
port                         config            -directedAddress                    "01 80 C2 00 00 01"
port                         config            -multicastPauseAddress              "01 80 C2 00 00 01"
port                         config            -loopback                           false
port                         config            -transmitMode                       portTxPacketStreams
port                         config            -receiveMode                        [expr $::portCapture]
port                         config            -autonegotiate                      false
port                         config            -advertise100FullDuplex             false
port                         config            -advertise100HalfDuplex             false
port                         config            -advertise10FullDuplex              false
port                         config            -advertise10HalfDuplex              false
port                         config            -advertise1000FullDuplex            true
#port                         config            -autonegotiate                      true
#port                         config            -advertise100FullDuplex             true
#port                         config            -advertise100HalfDuplex             true
#port                         config            -advertise10FullDuplex              true
#port                         config            -advertise10HalfDuplex              true
#port                         config            -advertise1000FullDuplex            true
port                         config            -portMode                           portEthernetMode
port                         config            -rxTxMode                           gigNormal
port                         config            -ignoreLink                         false
port                         config            -advertiseAbilities                 portAdvertiseSendAndOrReceive
port                         config            -timeoutEnable                      true
port                         config            -negotiateMasterSlave               0
port                         config            -masterSlave                        portSlave
port                         config            -enableSimulateCableDisconnect      false
port                         config            -enableAutoDetectInstrumentation    false
port                         config            -enableRepeatableLastRandomPattern  false
port                         config            -transmitClockDeviation             0
port                         config            -preEmphasis                        preEmphasis0
port                         config            -MacAddress                         "00 de bb 00 00 01"
port                         config            -DestMacAddress                     "00 de bb 00 00 02"
port                         config            -name                               "wan"
port                         config            -numAddresses                       1
port                         config            -enableManualAutoNegotiate          false
port                         config            -enablePhyPolling                   true
port                         set               $chassis $card $wanport
stat                         setDefault        
stat                         config            -mode                               statNormal
stat                         config            -enableProtocolServerStats          true
stat                         config            -enableArpStats                     true
stat                         config            -enablePosExtendedStats             true
stat                         config            -enableTemperatureSensorsStats      true
stat                         config            -enableAtmOamStats                  false
stat                         config            -enableDhcpStats                    false
stat                         config            -enableDhcpV6Stats                  false
stat                         config            -includeRprPayloadFcsInCrc          true
stat                         config            -enableValidStats                   false
stat                         config            -enableBgpStats                     false
stat                         config            -enableIcmpStats                    true
stat                         config            -enableOspfStats                    false
stat                         config            -enableIsisStats                    false
stat                         config            -enableRsvpStats                    false
stat                         config            -enableLdpStats                     false
stat                         config            -enableIgmpStats                    false
stat                         config            -enableOspfV3Stats                  false
stat                         config            -enablePimsmStats                   false
stat                         config            -enableMldStats                     false
stat                         config            -enableStpStats                     false
stat                         config            -enableEigrpStats                   false
stat                         set               $chassis $card $wanport

ipAddressTable               setDefault        
ipAddressTable               config            -defaultGateway                     "0.0.0.0"
ipAddressTable               set               $chassis $card $wanport
arpServer                    setDefault        
arpServer                    config            -retries                            3
arpServer                    config            -mode                               arpGatewayAndLearn
arpServer                    config            -rate                               2083333
arpServer                    config            -requestRepeatCount                 3
arpServer                    set               $chassis $card $wanport

interfaceTable               select            $chassis $card $wanport
interfaceTable               setDefault        
interfaceTable               config            -dhcpV4RequestRate                  0
interfaceTable               config            -dhcpV6RequestRate                  0
interfaceTable               set               
interfaceTable               clearAllInterfaces 
interfaceEntry               clearAllItems     addressTypeIpV6
interfaceEntry               clearAllItems     addressTypeIpV4
interfaceEntry               setDefault        

interfaceIpV4                setDefault        
interfaceIpV4                config            -gatewayIpAddress                   {192.168.3.1}
interfaceIpV4                config            -maskWidth                          24
interfaceIpV4                config            -ipAddress                          {192.168.3.10}
interfaceEntry               addItem           addressTypeIpV4

dhcpV4Properties             removeAllTlvs     
dhcpV4Properties             setDefault        
dhcpV4Properties             config            -clientId                           ""
dhcpV4Properties             config            -serverId                           "0.0.0.0"
dhcpV4Properties             config            -vendorId                           ""
dhcpV4Properties             config            -renewTimer                         0

dhcpV6Properties             removeAllTlvs     
dhcpV6Properties             setDefault        
dhcpV6Properties             config            -iaType                             dhcpV6IaTypePermanent
dhcpV6Properties             config            -iaId                               7323031
dhcpV6Properties             config            -renewTimer                         0

interfaceEntry               config            -enable                             true
interfaceEntry               config            -description                        {LAN}
interfaceEntry               config            -macAddress                         {00 00 00 6F BD 97}
interfaceEntry               config            -eui64Id                            {02 00 00 FF FE 6F BD 97}
interfaceEntry               config            -atmEncapsulation                   atmEncapsulationLLCBridgedEthernetFCS
interfaceEntry               config            -atmMode                            -1
interfaceEntry               config            -atmVpi                             0
interfaceEntry               config            -atmVci                             32
interfaceEntry               config            -enableDhcp                         false
interfaceEntry               config            -enableVlan                         false
interfaceEntry               config            -vlanId                             0
interfaceEntry               config            -vlanPriority                       0
interfaceEntry               config            -enableDhcpV6                       false
interfaceTable               addInterface      interfaceTypeConnected

protocolServer               setDefault        
protocolServer               config            -enableArpResponse                  true
protocolServer               config            -enablePingResponse                 false
protocolServer               config            -enableIgmpQueryResponse            false
protocolServer               config            -enableOspfService                  false
protocolServer               config            -enableBgp4Service                  false
protocolServer               config            -enableIsisService                  false
protocolServer               config            -enableRsvpService                  false
protocolServer               config            -enableRipService                   false
protocolServer               config            -enableLdpService                   false
protocolServer               config            -enableRipngService                 false
protocolServer               config            -enableMldService                   false
protocolServer               config            -enableOspfV3Service                false
protocolServer               config            -enablePimsmService                 false
protocolServer               config            -enableStpService                   false
protocolServer               config            -enableBgp4CreateInterface          false
protocolServer               config            -enableIsisCreateInterface          false
protocolServer               config            -enableOspfCreateInterface          false
protocolServer               config            -enableRipCreateInterface           false
protocolServer               config            -enableRsvpCreateInterface          false
protocolServer               config            -enableIgmpCreateInterface          false
protocolServer               set               $chassis $card $wanport

flexibleTimestamp            setDefault        
flexibleTimestamp            config            -type                               timestampBeforeCrc
flexibleTimestamp            config            -offset                             23
flexibleTimestamp            set               $chassis $card $wanport

capture                      setDefault        
capture                      config            -fullAction                         lock
capture                      config            -sliceSize                          8191
capture                      config            -sliceOffset                        0
capture                      config            -trigger                            -1
capture                      config            -filter                             -1
capture                      config            -captureMode                        captureContinuousMode
capture                      config            -continuousFilter                   1
capture                      config            -beforeTriggerFilter                captureBeforeTriggerNone
capture                      config            -afterTriggerFilter                 captureAfterTriggerFilter
capture                      config            -triggerPosition                    1.0
capture                      config            -enableSmallPacketCapture           false
capture                      set               $chassis $card $wanport
filter                       setDefault        
filter                       config            -captureTriggerDA                   anyAddr
filter                       config            -captureTriggerSA                   anyAddr
filter                       config            -captureTriggerPattern              anyPattern
filter                       config            -captureTriggerError                errAnyFrame
filter                       config            -captureTriggerFrameSizeEnable      false
filter                       config            -captureTriggerFrameSizeFrom        64
filter                       config            -captureTriggerFrameSizeTo          1518
filter                       config            -captureFilterDA                    addr1
filter                       config            -captureFilterSA                    addr1
filter                       config            -captureFilterPattern               anyPattern
filter                       config            -captureFilterError                 errAnyFrame
filter                       config            -captureFilterFrameSizeEnable       false
filter                       config            -captureFilterFrameSizeFrom         64
filter                       config            -captureFilterFrameSizeTo           1518
filter                       config            -userDefinedStat1DA                 anyAddr
filter                       config            -userDefinedStat1SA                 anyAddr
filter                       config            -userDefinedStat1Pattern            anyPattern
filter                       config            -userDefinedStat1Error              errAnyFrame
filter                       config            -userDefinedStat1FrameSizeEnable    false
filter                       config            -userDefinedStat1FrameSizeFrom      64
filter                       config            -userDefinedStat1FrameSizeTo        1518
filter                       config            -userDefinedStat2DA                 anyAddr
filter                       config            -userDefinedStat2SA                 anyAddr
filter                       config            -userDefinedStat2Pattern            pattern1
filter                       config            -userDefinedStat2Error              errGoodFrame
filter                       config            -userDefinedStat2FrameSizeEnable    1
filter                       config            -userDefinedStat2FrameSizeFrom      1518
filter                       config            -userDefinedStat2FrameSizeTo        1518
filter                       config            -asyncTrigger1DA                    anyAddr
filter                       config            -asyncTrigger1SA                    anyAddr
filter                       config            -asyncTrigger1Pattern               anyPattern
filter                       config            -asyncTrigger1Error                 errAnyFrame
filter                       config            -asyncTrigger1FrameSizeEnable       false
filter                       config            -asyncTrigger1FrameSizeFrom         64
filter                       config            -asyncTrigger1FrameSizeTo           1518
filter                       config            -asyncTrigger2DA                    anyAddr
filter                       config            -asyncTrigger2SA                    anyAddr
filter                       config            -asyncTrigger2Pattern               anyPattern
filter                       config            -asyncTrigger2Error                 errAnyFrame
filter                       config            -asyncTrigger2FrameSizeEnable       false
filter                       config            -asyncTrigger2FrameSizeFrom         64
filter                       config            -asyncTrigger2FrameSizeTo           1518
filter                       config            -captureTriggerEnable               true
filter                       config            -captureFilterEnable                true
filter                       config            -userDefinedStat1Enable             false
filter                       config            -userDefinedStat2Enable             false
filter                       config            -asyncTrigger1Enable                false
filter                       config            -asyncTrigger2Enable                false
filter                       set               $chassis $card $wanport
filterPallette               setDefault        
filterPallette               config            -DA1                                $da1
filterPallette               config            -DAMask1                            "00 00 00 00 00 07"
filterPallette               config            -DA2                                "00 00 00 00 00 00"
filterPallette               config            -DAMask2                            "00 00 00 00 00 00"
filterPallette               config            -SA1                                $sa1
filterPallette               config            -SAMask1                            "00 00 00 00 00 07"
filterPallette               config            -SA2                                "00 00 00 00 00 00"
filterPallette               config            -SAMask2                            "00 00 00 00 00 00"
filterPallette               config            -pattern1                           "DB 00 0A 02"
filterPallette               config            -patternMask1                       "00 00 00 00 00 00"
filterPallette               config            -pattern2                           00
filterPallette               config            -patternMask2                       00
filterPallette               config            -patternOffset1                     1504
filterPallette               config            -patternOffset2                     12
filterPallette               config            -matchType1                         matchUser
filterPallette               config            -matchType2                         matchUser
filterPallette               config            -patternOffsetType1                 filterPalletteOffsetStartOfFrame
filterPallette               config            -patternOffsetType2                 filterPalletteOffsetStartOfFrame
filterPallette               config            -gfpErrorCondition                  gfpErrorsOr
filterPallette               config            -enableGfptHecError                 true
filterPallette               config            -enableGfpeHecError                 true
filterPallette               config            -enableGfpPayloadCrcError           true
filterPallette               config            -enableGfpBadFcsError               true
filterPallette               set               $chassis $card $wanport
lappend                      portList          [list $chassis $card $wanport]

ixWritePortsToHardware       portList          
ixCheckLinkState             portList          


######### Chassis-192.168.20.194 Card-10  Port-2 #########

set streamId 1

#  Stream 1
stream                       setDefault        
stream                       config            -name                               ""
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          1
stream                       config            -ifg                                999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            1000.0
stream                       config            -bpsRate                            544000.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $da1
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $sa1
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "FF FF"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
stream                       config            -dma                                advance
#stream                       config            -dma                                contPacket
#stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               mac
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       noType
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       0
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0000XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $wanport

if {[port isValidFeature $chassis $card $wanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $wanport
}


if {[port isValidFeature $chassis $card $wanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $wanport
}

stream                       set               $chassis $card $wanport $streamId
incr                         streamId   

#  Stream 2
stream                       setDefault        
stream                       config            -name                               ""
stream                       config            -enable                             true
stream                       config            -region                             0
stream                       config            -numBursts                          1
stream                       config            -numFrames                          1
stream                       config            -ifg                                999392.0
stream                       config            -ifgType                            gapFixed
stream                       config            -ifgMIN                             192.0
stream                       config            -ifgMAX                             256.0
stream                       config            -ibg                                999392.0
stream                       config            -enableIbg                          false
stream                       config            -isg                                999392.0
stream                       config            -enableIsg                          false
stream                       config            -gapUnit                            gapNanoSeconds
stream                       config            -percentPacketRate                  0.0704
stream                       config            -fpsRate                            1000.0
stream                       config            -bpsRate                            544000.0
stream                       config            -rateMode                           usePercentRate
stream                       config            -preambleSize                       8
stream                       config            -sa                                 $da2
stream                       config            -saRepeatCounter                    idle
stream                       config            -saStep                             1
stream                       config            -saMaskValue                        "00 00 00 00 00 00"
stream                       config            -saMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableSaContinueFromLastValue      false
stream                       config            -da                                 $sa2
stream                       config            -daRepeatCounter                    idle
stream                       config            -daStep                             1
stream                       config            -daMaskValue                        "00 00 00 00 00 00"
stream                       config            -daMaskSelect                       "00 00 00 00 00 00"
stream                       config            -enableDaContinueFromLastValue      false
stream                       config            -framesize                          68
stream                       config            -frameSizeType                      sizeFixed
stream                       config            -frameSizeMIN                       68
stream                       config            -frameSizeMAX                       68
stream                       config            -frameSizeStep                      1
stream                       config            -enableTimestamp                    false
stream                       config            -fcs                                good
stream                       config            -patternType                        incrByte
stream                       config            -dataPattern                        x00010203
stream                       config            -pattern                            "00 01 02 03"
stream                       config            -frameType                          "FF FF"
stream                       config            -numDA                              16
stream                       config            -numSA                              16
#stream                       config            -dma                                advance
#stream                       config            -dma                                contPacket
stream                       config            -dma                                gotoFirst
stream                       config            -rxTriggerEnable                    false
stream                       config            -asyncIntEnable                     true
stream                       config            -loopCount                          1
stream                       config            -returnToId                         1
stream                       config            -enforceMinGap                      12
stream                       config            -enableSourceInterface              false
stream                       config            -sourceInterfaceDescription         ""
stream                       config            -startTxDelayUnit                   4
stream                       config            -startTxDelay                       0.0
protocol                     setDefault        
protocol                     config            -name                               mac
protocol                     config            -appName                            noType
protocol                     config            -ethernetType                       noType
protocol                     config            -enable802dot1qTag                  vlanSingle
protocol                     config            -enableISLtag                       false
protocol                     config            -enableMPLS                         false

vlan                         setDefault        
vlan                         config            -vlanID                             100
vlan                         config            -userPriority                       1
vlan                         config            -cfi                                resetCFI
vlan                         config            -mode                               vIdle
vlan                         config            -repeat                             10
vlan                         config            -step                               1
vlan                         config            -maskval                            "0000XXXXXXXXXXXX"
vlan                         config            -protocolTagId                      vlanProtocolTag8100
vlan                         set               $chassis $card $wanport

if {[port isValidFeature $chassis $card $wanport $::portFeatureTableUdf]} { 
	tableUdf setDefault
	tableUdf clearColumns
	tableUdf set $chassis $card $wanport
}


if {[port isValidFeature $chassis $card $wanport $::portFeatureRandomFrameSizeWeightedPair]} { 
	weightedRandomFramesize setDefault
	weightedRandomFramesize set $chassis $card $wanport
}

stream                       set               $chassis $card $wanport $streamId
incr                         streamId  
       
ixWriteConfigToHardware      portList          -noProtocolServer



after 2000
ixPuts "################### lanport upstream ######################"
#ixPuts "Removal of port information status message"
ixClearPortStats $chassis $card $lanport
ixClearPortStats $chassis $card $wanport
after 1000
#ixPuts "Match flow open port, message collection and contrast"
ixStartPortTransmit $chassis $card $lanport
ixStartPortCapture $chassis $card $wanport
after 5000
#ixCheckPortTransmitDone $chassis $card $lanport
ixStopPortCapture $chassis $card $wanport
ixStopPortTransmit $chassis $card $lanport

captureBuffer get $chassis $card $wanport 1 10

set Flag1 0
set Mark1 0
for {set i 1} {$i <= 10} {incr i} {
	if { [captureBuffer getframe $i] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	      set capFrame [captureBuffer cget -frame]
	      set typeField [lrange $capFrame 0 15]
	      set tarValue [format "%s %s 81 00 00 64" $da1 $sa1 ]
		  if {$typeField == $tarValue	} {
             incr Flag1
	         ixPuts "It is expected that receiving a Vlan=100 Priority=0 upstream stream1 ."
	         break
	      } else { 
	             incr Mark1 
	             puts $typeField
	      }
    }	
}
if {$Mark1 == 10} {
    ixPuts "error ! not receiving a Vlan=100 Priority=0 upstream stream1"
}


set Flag2 0
set Mark2 0
for {set j 1} {$j <= 10} {incr j} {
	if { [captureBuffer getframe $j] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $wanport"	
	   break
	} else {
	      set capFrame [captureBuffer cget -frame]
	      set typeField [lrange $capFrame 0 15]
	      set tarValue [format "%s %s 81 00 20 64" $da2 $sa2 ]
		  if {$typeField == $tarValue	} {
             incr Flag2
	         ixPuts "It is expected that receiving a Vlan=100 Priority=1 upstream stream2 ."
	         break
	      } else { 
	             incr Mark2 
	             puts $typeField
	      }
    }	
}
if {$Mark2 == 10} {
    ixPuts "error ! not receiving a Vlan=100 Priority=1 upstream stream2"
}






ixPuts "################### wanport downstream ######################"
#ixPuts "Removal of port information status message"
ixClearPortStats $chassis $card $wanport
ixClearPortStats $chassis $card $lanport
after 1000

ixStartPortTransmit $chassis $card $wanport
ixStartPortCapture $chassis $card $lanport
after 5000

ixStopPortCapture $chassis $card $lanport
ixStopPortTransmit $chassis $card $wanport

captureBuffer get $chassis $card $lanport 1 10


#TCL API执行成功返回0 不进入if语句；执行失败返回1，进入if语句

set Flag3 0
set Mark3 0
for {set m 1} {$m <= 10} {incr m} {
	if { [captureBuffer getframe $m] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $lanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 15]
	       set tarValue [format "%s %s 81 00 40 64" $sa1 $da1 ]
	       if {$typeField == $tarValue} {
               incr Flag3
	           ixPuts  "It is expected that receiving a Vlan=100 Priority =2 downstream stream1 ."
	           break
	       } else { 
	              puts $typeField
	              incr Mark3
	       }
    }
}	
if {$Mark3 == 10} {
    ixPuts "Error ! not receiving Vlan=100 Priority =2 downstream stream1."
}


set Flag4 0
set Mark4 0
for {set n 1} {$n <= 10} {incr n} {
	if { [captureBuffer getframe $n] } {
	   ixPuts "Error ! failed to get captureBuffer on $chassis $card $lanport"	
	   break
	} else {
	       set capFrame [captureBuffer cget -frame]
	       set typeField [lrange $capFrame 0 15]
	       set tarValue [format "%s %s 81 00 60 64" $sa2 $da2 ]
	       if {$typeField == $tarValue} {
               incr Flag4
	           ixPuts  "It is expected that receiving a Vlan=100 Priority =3 downstream stream2 ."
	           break
	       } else { 
	              puts $typeField
	              incr Mark4
	       }
    }
}	
if {$Mark4 == 10} {
    ixPuts "Error ! not receiving Vlan=100 Priority =3 downstream stream2."

set Flag [expr $Flag1 + $Flag2 +$Flag3 +$Flag4 ]
if {$Flag == 4} {
	ixPuts "#########################  result  #####################"
	puts "this case pass!"
	ixPuts "########################################################"
} else {
	ixPuts "#########################  result  #####################"
	puts "this case fail!"
	ixPuts "########################################################"
}
